### PR TITLE
Use Github enterprise api URL and user access token to fetch user details

### PR DESCRIPTION
**Pull request by rathourarv**

### CODE REVIEW

**Comment by arvindsv** [comment]
I've added a comment about this in #11 .

**Comment by bdpiparva** [comment]
@vrushaliwaykole is looking at the PR.

**Comment by vrushaliwaykole** [comment]
Verified

1. Tested with GitHub enterprise application
2. Tested with a normal GitHub account

Authentication works fine in both cases. 

\cc @bdpiparva

**Comment by bdpiparva** [comment]
@rathourarv - Stable release with your changes are available at https://github.com/gocd-contrib/github-oauth-authorization-plugin/releases/tag/v3.0.2-57

**Pull request merged**
