### PR TITLE
Option to use personal access token over read:org permission on user's access token

### PR DESCRIPTION
**Pull request by bdpiparva**
- Allow admin to choose authorization using `PersonalAccessToken` or `UserAccessToken`

	- PersonalAccessToken: requires an additional `read:org` permission on `PersonalAccessToken` to authorize user based on role configuration.
	- UserAccessToken: requires an additional `read:org` permission
from user. This allows plugins to access private org and teams of user.

### CODE REVIEW

**Comment by arvindsv** [comment]
Can you also update INSTALL.md as a part of this or separately? I think it needs a lot of work - it's not clear at all what is possible, don't you think?

**Comment by bdpiparva** [comment]
Yes, I will update the INSTALL.md file separately.

**Comment by ketan** [comment]
> Yes, I will update the INSTALL.md file separately.

Having a step-by-step guide with screenshots would be very nice to have, since users mostly get it wrong.

**Comment by bdpiparva** [comment]
> Having a step-by-step guide with screenshots would be very nice to have, since users mostly get it wrong.

Sure.

**Pull request merged**
