### PR TITLE
fix the v3 API url for github enterprise

### LINKED ISSUE #11: GitHub Enterprise integration broken
Although the API space in github enterprise is `/api/v3` which needs to be present in the configured github URL, for the login flow the `/api/v3` part needs to be omitted.

### PR DESCRIPTION
**Pull request by yikaus**
resolve #11 

apiUrl is design for api endpoint , refactor this value won't affect authentication url which is gitHubEnterpriseUrl.

@chringwer 's fix adding hostUrl seems duplicate with apiUrl ,also need to add /api/v3 when user configure server name in UI

### CODE REVIEW

**Comment by ksegun** [comment]
This fix did not work when we tried it, went with the one from @chringwer does.

**Comment by yikaus** [comment]
@ksegun Can I ask what URL you input for github enterprise ? 

unlike @chringwer 's approach , You should not add /api/v3 as part of github enterprise URL . as handler will add it for you.

**Comment by ksegun** [comment]
@yikaus Yes  it looks like we had /api/v3 as part of the URL.

**Comment by LaoLiulaoliu** [comment]
hi @yikaus , can you merge this and build a new release. This really solve the enterprise github problem. Thanks a lot

**Comment by yikaus** [comment]
The PR has defect ,@chringwer is one which able to use.

**Pull request closed without merging**
